"""empty message

Revision ID: 0df07541b1ea
Revises: b2f70bc021a0
Create Date: 2023-03-26 23:49:38.286523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0df07541b1ea'
down_revision = 'b2f70bc021a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.alter_column('release_date',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.alter_column('release_date',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
