"""empty message

Revision ID: b2f70bc021a0
Revises: 86467f72f60e
Create Date: 2023-03-24 14:32:06.113963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2f70bc021a0'
down_revision = '86467f72f60e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlists_songs',
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('song_id', 'playlist_id')
    )
    op.drop_table('playlistsongs')
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.alter_column('release_date',
               existing_type=sa.DATETIME(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.alter_column('release_date',
               existing_type=sa.String(),
               type_=sa.DATETIME(),
               existing_nullable=False)

    op.create_table('playlistsongs',
    sa.Column('songs.id', sa.INTEGER(), nullable=False),
    sa.Column('playlists.id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['playlists.id'], ['playlists.id'], ),
    sa.ForeignKeyConstraint(['songs.id'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('songs.id', 'playlists.id')
    )
    op.drop_table('playlists_songs')
    # ### end Alembic commands ###
